// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: server.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ServiceServer_SayHi_FullMethodName = "/serviceServer/sayHi"
)

// ServiceServerClient is the client API for ServiceServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceServerClient interface {
	SayHi(ctx context.Context, in *CliRequest, opts ...grpc.CallOption) (*SerResponse, error)
}

type serviceServerClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceServerClient(cc grpc.ClientConnInterface) ServiceServerClient {
	return &serviceServerClient{cc}
}

func (c *serviceServerClient) SayHi(ctx context.Context, in *CliRequest, opts ...grpc.CallOption) (*SerResponse, error) {
	out := new(SerResponse)
	err := c.cc.Invoke(ctx, ServiceServer_SayHi_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServerServer is the server API for ServiceServer service.
// All implementations must embed UnimplementedServiceServerServer
// for forward compatibility
type ServiceServerServer interface {
	SayHi(context.Context, *CliRequest) (*SerResponse, error)
	mustEmbedUnimplementedServiceServerServer()
}

// UnimplementedServiceServerServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServerServer struct {
}

func (UnimplementedServiceServerServer) SayHi(context.Context, *CliRequest) (*SerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHi not implemented")
}
func (UnimplementedServiceServerServer) mustEmbedUnimplementedServiceServerServer() {}

// UnsafeServiceServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServerServer will
// result in compilation errors.
type UnsafeServiceServerServer interface {
	mustEmbedUnimplementedServiceServerServer()
}

func RegisterServiceServerServer(s grpc.ServiceRegistrar, srv ServiceServerServer) {
	s.RegisterService(&ServiceServer_ServiceDesc, srv)
}

func _ServiceServer_SayHi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CliRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServerServer).SayHi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceServer_SayHi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServerServer).SayHi(ctx, req.(*CliRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceServer_ServiceDesc is the grpc.ServiceDesc for ServiceServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "serviceServer",
	HandlerType: (*ServiceServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sayHi",
			Handler:    _ServiceServer_SayHi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
